apiVersion: v1
kind: Service    #类型Service
metadata:        #元数据
  name: mysql    #service名称mysql
spec:
  ports:
    - port: 3306  #service提供的服务端口
  selector:       #serviced对应Pod拥有的标签
    app: mysql   
