apiVersion: v1
kind: ReplicationController   #副本控制器
metadata:
  name: mysql                 #RC的名称，全局唯一
spec:
  replicas: 0                 #副本的期望数量
  selector:                   #选择器
    app: mysql                #符合目标的Pod拥有的标签
  template:                   #Pod的模板，根据此模板创建Pod的副本实例
    metadata:                 
      labels:                 #标签
        app: mysql            #Pod副本的标签名，对应RC的selector
    spec:                     
      containers:             #容器
      - name: mysql           #容器名
        image: hub.c.163.com/library/mysql:8.0.1          #镜像
        ports:                #端口
        - containerPort: 3306 #容器监听的端口
        env:                  #环境变量
        - name: MYSQL_ROOT_PASSWORD  #MYSQL密码
          value: "123456"
