apiVersion: v1
kind: ReplicationController      #副本控制器RC
metadata:                        #元数据
  name: mysql                    #RC的名称，全局唯一
spec:                            #说明
  replicas: 1                    #Pod副本的期待数量
  selector:                      #选择器
    app: mysql                   #符合目标的Pod拥有此标签
  template:                      #根据此模板创建Pod的副本(实例)
    metadata:
      labels:                    #标签
        app: mysql               #Pod副本拥有的标签，对应RC的Selector
    spec:
      containers:                #Pod内容器的定义部分
      - name: mysql              #容器的名称
        image: hub.c.163.com/library/mysql:8.0.1   #容器对应的docker image
        resources:               #资源分配
          requests:              #资源最小申请量
            memory: "64Mi"       #定义最小使用内存大小
            cpu: "250m"          #定义最小使用cpu大小
          limits:                #资源最大允许使用量
            memory: "128Mi"      #内存最大使用量
            cpu: "500m"          #cpu最大使用量
        ports:
        - containerPort: 3306    #容器应用监听的端口号
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
