apiVersion: v1
kind: Pod      #定义这是一个Pod
metadata:      #元数据 
  name: myweb  #Pod的名称
  labels:      #标签
    app: myweb #标签名称
spec:          #定义容器里的内容
  containers:  #容器
  - name: myweb #容器名
    image: kubeguide/tomcat-app:v1 #容器镜像版本
    ports:     #端口
    - containerPort: 8080    #容器端口
    env:                     #变量
    - name: MYSQL_SERVICE_HOST   #变量名
      value: 'mysql'           #变量值
    - name: MYSQL_SERVICE_PORT  #变量名
      value: '3306'            #变量值
