apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler    #定义类型HPA
metadata:
  name: php-apache       #定义HPA控制的目标对象为php-apache的deployment里的Pod副本
  namespace: default
spec:
  maxReplicas: 10       #最大扩容副本数
  minReplicas: 1        #最小缩容副本数
  scaleTargetRef:
    kind: Deployment    #监控的对象deployment
    name: php-apache    #pod的名称
  targetCPUUtilizationPercentage: 90  #CPU使用率90



