apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  type: NodePort    #指定Port类型
  ports:
  - port: 8080       #service服务端口
    nodePort: 31080  #指定nodeport端口
  selector:
    tier: frontend   #标签 frontend
